package com.manuanand.readmore;

import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/reader") // This means URL's start with /readmore (after Application path)
public class ReaderController {
	@Autowired // This means to get the bean called readerRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private ReaderRepository readerRepository;
	
	///
	// Reader Repository
	///
	@PostMapping(path="/addReader") // Map ONLY POST Requests
	public @ResponseBody String addReader (@RequestParam String name, 
			@RequestParam String email, @RequestParam String password) {

		Reader newReader = new Reader();
		newReader = populateReader(newReader, name, email, password);
		readerRepository.save(newReader);
		
		return "Saved";
	}

	@GetMapping(path="/getAllReaders")
	public @ResponseBody Iterable<Reader> getReaders() {
		
		// This returns a JSON or XML with the users
		return readerRepository.findAll();
	}
	
	@GetMapping(path="/getReaderById")
	public @ResponseBody Reader getReaderById(@RequestParam int id) {
		
		Optional<Reader> reader = readerRepository.findById(id);
		if (!reader.isEmpty()) {
			return reader.get();
		} 
		
		return null;
	}
	
	///
	/// Helper Methods
	///
	private Reader populateReader( Reader newReader, String name, String email, String password)
	{
		newReader.setName(name);
		newReader.setEmail(email);
		newReader.setPassword(password);
		
		return newReader;
	}
}